# Generated by Django 4.1.3 on 2022-11-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/resume_images')),
                ('job', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(1, 'Men'), (2, 'Fimale'), (1, 'No Gender')], max_length=150)),
                ('age', models.FloatField()),
                ('phone', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Resume',
            },
        ),
    ]
