# Generated by Django 4.1.3 on 2022-11-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='media/category_images')),
            ],
            options={
                'verbose_name_plural': '1. Category',
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': '2. Resume'},
        ),
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs_app.category'),
            preserve_default=False,
        ),
    ]
