# Generated by Django 4.1.3 on 2022-11-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_aboutyou'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutyou',
            options={'verbose_name_plural': '8. About You'},
        ),
    ]
