# Generated by Django 4.1.3 on 2022-11-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0010_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name_plural': '9. Paid Status'},
        ),
    ]
