# Generated by Django 4.1.3 on 2022-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0012_hrregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrregister',
            name='role',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
