# Generated by Django 4.1.3 on 2022-12-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0015_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
