# Generated by Django 4.1.3 on 2022-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0018_blog_blogcategory_blogcomment_replayoncomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=1, upload_to='media/blog_images'),
            preserve_default=False,
        ),
    ]
