# Generated by Django 4.1.3 on 2022-12-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0020_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
