# Generated by Django 4.1.3 on 2022-12-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0035_blog_blogcategory_blogcomment_replayoncomment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplayOnComment',
        ),
    ]
